### ISSUE TITLE
a detailed guide on how to download,install and run pls

### ISSUE THREAD

**Issue by ineeddankselfbots** [Sxvxgee/WhiteFlow#4]
thank you in advance

**Comment by ThePrivatePanda** [comment]
Planned, will be implemented when WhiteFlow is a useable piece of software.

**Comment by skifli** [comment]
@ineeddankselfbots  The reason such a piece of documentation does not exist already is because WhiteFlow is not finished yet. Once it reaches a stable version, the relevant pieces of documentation (including installation guide) will be released.

**Comment by theAbdoSabbagh** [comment]
Documentation will be added soon, until then if you're facing issues you're more than welcome to use the Discussions tab and post your questions there, and you can also join the Discord server, it's linked in the README at the bottom.
